DATASET: 'scannet'
BATCH_SIZE: 4
SAVE_SCENE_MESH: False
LOGDIR: './checkpoints'
SAVE_FREQ: 1
MODE: 'train'
RESUME: True
LOADCKPT: './checkpoints/Voxel_Img_Feats_24_07_25/model_000099.ckpt'

TRAIN:
  PATH: 'datasets/scannet'
  EPOCHS: 100  # 30, 55
  N_VIEWS: 9
  LR: 1e-4
  N_WORKERS: 8
  LREPOCHS: '70,90:10'  # '6,12,24:2', '20,25:10', '35,45:10'
  ACCUMULATION_STEPS: 8
  ONLY_INIT: False
  ONLY_OCC: False
  AUTOGRAD: False

TEST:
  PATH: 'datasets/scannet'
  N_VIEWS: 9
  N_WORKERS: 4

MODEL:
  N_LAYER: 3
  N_VOX: [96, 96, 96]
  VOXEL_SIZE: 0.04
  TRAIN_NUM_SAMPLE: [15000, 60000, 120000]
  TEST_NUM_SAMPLE: [15000, 60000, 120000]

  BACKBONE2D:
    ARC: 'fpn-mnas-1'

  FUSION:
    FUSION_ON: True
    HIDDEN_DIM: 64

    AVERAGE: False
    FULL: True

  LW: [1.0, 0.8, 0.64, 1.2]

  THRESHOLDS: [0, 0, 0]
  POS_WEIGHT: 1.5
